### ISSUE TITLE
Unable to get the project to build using VS2022

### ISSUE THREAD

**Issue by aybe** [VelocityRa/pctation#2]
Hello,

I've been trying to get the project to build by launching `setup-windows.bat` but I'm granted with the following:

```
Could not find MSBuild version with C++ support. VS2015, VS2017, or VS2019 (with C++) needs to be installed.
At C:\Users\aybe\source\repos\pctation\external\vcpkg\scripts\bootstrap.ps1:195 char:5
+     throw "Could not find MSBuild version with C++ support. VS2015, V ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find MSBuild version with C++ support. VS2015, VS2017, or VS2019 (with C++) ne
   eds to be installed.

```

I've tried to install the _Desktop development with C++_ package on Visual Studio 2022 but that didn't have any effect.

Any ideas on how to get the project to build?

Thank you.

**Comment by Zangetsu38** [comment]
project no supported 2022 yet

**Comment by aybe** [comment]
I have been able to get it to build for 2022, not without trouble however 😅.

Here's the PR: #3 

You will most definitely want to adjust the last commit as IMO it's a wrong approach but I really have no idea on how to solve the problem.

Thanks mate 😀
